// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Oid85.Health.Infrastructure;

#nullable disable

namespace Oid85.Health.Infrastructure.Migrations
{
    [DbContext(typeof(HealthContext))]
    [Migration("20260101133128_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityAlwaysColumns(modelBuilder);

            modelBuilder.Entity("Oid85.Health.Infrastructure.Entities.GlucoseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("AfterMorningFood")
                        .HasColumnType("double precision");

                    b.Property<double?>("AfterTraining")
                        .HasColumnType("double precision");

                    b.Property<double?>("BeforeEveningFood")
                        .HasColumnType("double precision");

                    b.Property<double?>("BeforeMorningFood")
                        .HasColumnType("double precision");

                    b.Property<double?>("BeforeNight")
                        .HasColumnType("double precision");

                    b.Property<double?>("BeforeTraining")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("GlucoseEntities", "public");
                });

            modelBuilder.Entity("Oid85.Health.Infrastructure.Entities.PressureEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Dia")
                        .HasColumnType("integer");

                    b.Property<int?>("Pulse")
                        .HasColumnType("integer");

                    b.Property<int>("Sys")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.ToTable("PressureEntities", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
